### ISSUE TITLE
Can't install extension "Failed to copy directory" - MacOS Catalina 

### ISSUE THREAD

**Issue by Jsalas424** [stephan1312/SlicerEAMapReader#2]
Hi, 

I downloaded SlicerEAMapReader-master.zip and tried to install your extension but the following error: 
```
Failed to copy directory /Applications/Slicer.app/Contents/Extensions-29402/EAMapReader/SlicerEAMapReader-master/Slicer.app/Contents/Extensions-29402/EAMapReader into directory /Applications/Slicer.app/Contents/Extensions-29402/EAMapReader-XXXXXX
```
I unzipped the master folder and then tried to install EAMapReader-Slicer-4.11.zip and got the same error.
```
ctk::copyDirRecursively: Failed to copy nonexistent directory "/Applications/Slicer.app/Contents/Extensions-29402/EAMapReader/EAMapReader-Slicer-4.11/Slicer.app/Contents/Extensions-29402/EAMapReader"
"Failed to copy directory /Applications/Slicer.app/Contents/Extensions-29402/EAMapReader/EAMapReader-Slicer-4.11/Slicer.app/Contents/Extensions-29402/EAMapReader into directory /Applications/Slicer.app/Contents/Extensions-29402/EAMapReader-XXXXXX"
```

 I renamed the file "EAMapReader.zip" but still nothing. I moved all the files to my desktop and tried from there - no luck. 

I'm on a Macbook Pro Catalina, any advice would be greatly appreciated!

**Comment by Jsalas424** [comment]
Following up on this, a friend was able to install using the master zip file on Windows 10.

**Comment by stephan1312** [comment]
There are some issues with the installation from zip on a mac. Try to copy the python script to a folder an install the module manually as follows:

1. First, uninstall the failed EAMapReader installation through the Extension Manager (you have to restart after that)
2. From the zip file, take the folder EAMapReader-Slicer-4.11 and copy it (with all its subfolders) to some location on your hard disk
3. In Slicer, go to Edit - > Application Settings -> Modules panel -> click the [>>] next to the “Additional module paths” area and click “Add”  
4. A file dialog opens. Go to the folder where you copied the EAMapReader-Slicer-4.11 folder, then navigate to the subfolder …/EAMapReader-Slicer-4.11/lib/Slicer-4.11/qt-scripted-modules
5. Chose that folder, then restart Slicer.
 
By doing so, you should be able to force Slicer to load that module, even if the install does not work. Let me know if it works for you.

**Comment by Jsalas424** [comment]
I don't actually see the application in the extension manager, so skipped step 1. The rest of the steps seemed to have worked though! Will report back if we have any more issues, thanks! 
<img width="1440" alt="Screen Shot 2020-11-28 at 8 06 44 AM" src="https://user-images.githubusercontent.com/51519895/100516268-b6dccb00-3150-11eb-8ca2-bb5253a83fc0.png">
