### ISSUE TITLE
How to open data in Carto3 v4

### ISSUE THREAD

**Issue by ipoirot** [stephan1312/SlicerEAMapReader#8]
Hi all,

I have just seen your paper, nice work!
I'm wondering how to open data exported in Carto3 v4. The EA map was acquired using the CARTO 3 version 4.3.5.91 mapping system. 

Thanks in advance for your help!

Wang Shuo

**Comment by ipoirot** [comment]
Here's what the inner folder looks like:
![image](https://user-images.githubusercontent.com/40530799/134309818-5c3fcfd0-017b-4cf0-8416-f108478b2276.png)

**Comment by ipoirot** [comment]
The attached mesh file is written in binary. I have no idea how to open it.
[MapSurface.zip](https://github.com/stephan1312/SlicerEAMapReader/files/7215271/MapSurface.zip)

**Comment by stephan1312** [comment]
You need to export the data. There was a dedicated export functionality even in v4. (Actually, the very first data I used for creating EAMapReader was animal data obtained on a CARTO3 v4 system. Back then, I took pictures of the export workflow to instruct my colleagues, you can find them below)
In short: Open the study for review and click Study->export study data from the menu. Close the study, then (from the first menu that opens after starting the workstation) select "System" and from the menu that pops up, select Export data. Select the zip file from the list and export it to the external drive.
This is the zip file which can be read by EAMapReader.

The folder structure and binary file you shared is the proprietary format in which the studies are saved on the workstation. To my knowledge this cannot be read by any external software.

![20190129_135445](https://user-images.githubusercontent.com/33878842/134710819-ba5ba000-01c6-408b-81c7-fd7059b65eca.jpg)
![20190129_135455](https://user-images.githubusercontent.com/33878842/134710842-49b769dc-3b9c-428b-b531-f34306558496.jpg)
![20190129_135539](https://user-images.githubusercontent.com/33878842/134710859-d3013a89-3776-4a59-8567-88863f1c418a.jpg)
![20190129_135649](https://user-images.githubusercontent.com/33878842/134710872-dc329c6d-8788-49c7-932b-815661606da7.jpg)
![20190129_135653](https://user-images.githubusercontent.com/33878842/134710881-fe7fe059-7d5f-46e2-b4a6-2e3129ca768c.jpg)
![20190129_135736](https://user-images.githubusercontent.com/33878842/134711050-63cf5dd5-cb77-4161-a902-d5c2090c2982.jpg)
![20190129_135903](https://user-images.githubusercontent.com/33878842/134711083-4f530a80-eb71-4de8-91dd-8b964e316ed9.jpg)

**Comment by ipoirot** [comment]
Thanks a lot for your detailed reply, it's very helpful.
