### ISSUE TITLE
Problem with import data

### ISSUE THREAD

**Issue by jstaniec** [stephan1312/SlicerEAMapReader#9]
Can anyone help me solve the problem with data import from Ensite NavX. While importing, I get the following error:
![image](https://user-images.githubusercontent.com/61056620/151955991-b6503521-0138-42d4-9c4f-f2a38a52dfcd.png)
I will be grateful for the help provided.

**Comment by stephan1312** [comment]
I will try to reproduce the issue once I am home (currently travelling).
Which version of 3D Slicer are you using?
Also, could you (maybe via direct message) share the anonymized NavX .xml file that caused the problen?
I will get back to you a.s.a.p.

**Comment by jstaniec** [comment]
Hi Stphan. Thanks for your help. My 3D Slicer version is 4.11.20210226 r29738. I attach xml files to your analysis.
[xml_files.zip](https://github.com/stephan1312/SlicerEAMapReader/files/7993199/xml_files.zip)

**Comment by stephan1312** [comment]
There are two xml files in the zip. The file DxLandmarkGeo.xml adheres to the usual NavX export format and can be read (on my system) as expected. The containing geometry consists of two models with some electrical information (probably bipolar voltage, judging from the range of values, but this is something which is defined at export time in NavX):
![Bild1](https://user-images.githubusercontent.com/33878842/152607997-f16c5251-01b3-4383-a38d-fcb1bd4909f9.png)

The other one, ModelGroups.xml, seems to lack some fields such as the scalar map data (voltage or LAT, i.e. the "coloring"). How did you create the ModelGroups.xml? What information is in there, i.e. what should be imported beyond the data contained in DxLandmarkGeo.xml? If there is something you need from that other file, I could maybe extend the EAMapReader functionality to read that file, as well.

**Comment by jstaniec** [comment]
Hi Stephen, 
Sorry for my delay but I had problem with my health. Your screen looks like what I need that is bioporal voltage.  I had a problem to import DxLandmarkGeo.xml to 3D Slicer. My import stuck on 15% with error as abowe. Mayby I try reinstall my software and I will try import data again. I will back with results soon.

**Comment by jstaniec** [comment]
HI Stephen,
Can you provide me, how did you get model as on your screen ? When I try to import the same file DxLandmarkGeo.xml, I get a single color solid but I need colored information on biopolar voltage. Maybe I need switch something on my 3DSlicer?

![image](https://user-images.githubusercontent.com/61056620/160353144-921a9b6e-d38d-4170-b013-e723131de0ae.png)

Thanks for your help.

**Comment by jstaniec** [comment]
And in my python interagcrot I get the following information:

![image](https://user-images.githubusercontent.com/61056620/160353458-c0c4d935-bf45-4f59-bdd3-893c807ae1e6.png)

**Comment by stephan1312** [comment]
> 

This is just a warning that some feature will be deprecated in future Python versions, nothing to worry about today and nothing that should currently impair functionality.

**Comment by stephan1312** [comment]
> HI Stephen, Can you provide me, how did you get model as on your screen ? When I try to import the same file DxLandmarkGeo.xml, I get a single color solid but I need colored information on biopolar voltage. Maybe I need switch something on my 3DSlicer?
> 
> ![image](https://user-images.githubusercontent.com/61056620/160353144-921a9b6e-d38d-4170-b013-e723131de0ae.png)
> 
> Thanks for your help.

You can color the model according to the model scalars. 
Models module -> Scalars fold-out -> Check "Visible" -> Active Scalar "MapData" (for Ensite - the scalar sets have different labels for different mapping systems) -> Color table "Rainbow" (or whatever you like best, but rainbow resembles the Carto colors and to some extent the Ensite colors) -> Scalar Range Mode "Manual" -> Displayed Range [depending on the scalar data at hand]

Something similar to this (please ignore the red marking, that was for another tutorial):

![grafik](https://user-images.githubusercontent.com/33878842/160799941-69b2219d-6ec5-4344-80bf-fd32c5513b2c.png)


Hope that helps.

Best regards
Stephan

**Comment by jstaniec** [comment]
Thanks for your assistance, your help was unbelievable.
